folio-org/mod-invoice

- descriptors/ModuleDescriptor-template.json
Missed a permission in the scope of https://issues.folio.org/browse/MODINVOICE-50
Add the missing permission to GET /invoice/invoice-lines/{id}
> Adding Missing Permissions

- pom.xml
- src/main/java/org/folio/invoices/utils/InvoiceLineProtectedFields.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/resources/mockdata/invoices/3ff985f9-27dc-40c9-b495-1f54d2af6700.json
- src/test/resources/mockdata/invoices/52fd6ec7-ddc3-4c53-bc26-2779afc27136.json
- src/test/resources/mockdata/invoices/c0d08448-347b-418a-8c2f-5fb50248d67e.json
[MODINVOSTO-22](https://issues.folio.org/browse/MODINVOSTO-22) Remove invoice.acquisitionsUnit
[MODINVOICE-60](https://issues.folio.org/browse/MODINVOICE-60) Invoice schemas - readonly properties
- pointing to updated acq-models sub-module
- RMB version is `25.0.1`
- updating mock data and validation
> MODINVOSTO-22/MODINVOICE-60 Schema updates

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VoucherLineHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
[MODINVOICE-36](https://issues.folio.org/browse/MODINVOICE-36) Mark voucher as paid on transition to invoice status "Paid"
- When the invoice's status is being updated to `Paid`:
- Get voucher by invoice id. If not found, complete flow with `voucherNotFound` error
- Check voucher's status: 
- if it is not yet Paid, update status to Paid and store updated voucher. In case f failure complete flow with `voucherUpdateFailure` error
- otherwise do nothing
- Other improvements:
- Return `poLineUpdateFailure` error if PO Line's update failed
- Update `ResourcePathResolver#resourceByIdPath` method adding `lang` param
- Does this introduce …
> MODINVOICE-36 Mark voucher as paid on transition to invoice status "Paid"

- src/test/resources/mockdata/poLines/0009662b-8b80-4001-b704-ca10971f175d.json
- src/test/resources/mockdata/poLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
[MODORDERS-247](https://issues.folio.org/browse/MODORDERS-247) Make contributor-name-type configurable …
> MODORDERS-247 Make contributor-name-type configurable

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/invoices/events/handlers/InvoiceSummary.java
- src/main/java/org/folio/invoices/events/handlers/MessageAddress.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/InitEventBus.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VoucherLineHelper.java
- src/test/java/org/folio/invoices/events/handlers/InvoiceSummaryTest.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-87](https://issues.folio.org/browse/MODINVOICE-87) Calculate and persist totals upon invoice creation/update/get
- Updating invoice totals before storing it in DB on `POST`, `PUT` operations
- Updating invoice totals and storing it async (without blocking main operation) in DB on `GET` invoice by id operations if out of sync
- When invoice line is created, updated or deleted an event is triggered to update invoice totals
***Note:*** the acq unit assignments permissions are removed because they are not needed anymore
> MODINVOICE-87 Calculate and persist totals upon invoice creation/update/get

- descriptors/ModuleDescriptor-template.json
[MODINVOICE-87](https://issues.folio.org/browse/MODINVOICE-87) Calculate and persist invoice totals
This is follow on changes to https://github.com/folio-org/mod-invoice/pull/55: update module permission to let async invoice update to work when invoice line totals are changed
> MODINVOICE-87 Calculate and persist invoice totals upon invoice line creation/update/delete

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/events/handlers/InvoiceSummary.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/InvoiceLineProtectedFields.java
- src/main/java/org/folio/invoices/utils/InvoiceProtectedFields.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/test/java/org/folio/invoices/events/handlers/InvoiceSummaryTest.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/invoiceLines/55e4b6f5-f974-42da-9a77-24d4e8ef0e70.json
[MODINVOICE-87](https://issues.folio.org/browse/MODINVOICE-87) Calculate and persist invoice totals
[MODINVOICE-86](https://issues.folio.org/browse/MODINVOICE-86) Calculate and persist invoice line totals on creation
[MODINVOICE-87](https://issues.folio.org/browse/MODINVOICE-87):
- Trigger calculations only if invoice is still open for modifications i.e. status is `OPEN` or `REVIEWED`
- When invoice line is retrieved and totals are outdated, the record is persisted in storage and on success triggers an event to update invoice
- Adding `adjustmentsTotal`, `subTotal` and `total` as protected i.e. cannot be modified anymore after invoice approval
[MODINVOICE-86](https://issues.folio.org/browse/MODINVOICE-86):
- Updating logic to store invoice line totals in storage
- Adding unit tests to …
> MODINVOICE-87 Calculate and persist invoice totals upon invoice line updates

- src/test/resources/mockdata/acquisitionUnits/units.json
[MODORDERS-293](https://issues.folio.org/browse/MODORDERS-293) Acquisition units - soft delete
Pointing to latest acq-models with required schema changes
> MODORDERS-293 Acquisition units - soft delete

- pom.xml
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/ProtectionHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/protection/InvoicesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/ProtectedEntityTestBase.java
https://issues.folio.org/browse/MODINVOICE-89
- On invoice creation: in case any acq units assigned, check first if all exist and have `isDeleted==false`
- On invoice update: in case any acq units assigned, check that all newly assigned acq units (comparing to what is in storage) exist and have `isDeleted==false`
- Handle case when only one unit assigned to invoice and it has isDeleted==true - no need to check user memberships
In both cases above on failure, the flow is terminated and an error is returned to the client like following
```json
{
"message": "Acquisitions units assigned to invoice not found",
"code": "acqUnitsNotFound",
"acqUnitIds": [
"a968d9fe-1230-4c44-8e59-87cd462a06e4",
"eab71dbd-b14b-4cfb-9b1e-d6f450b5b00f"
]
}
```
Before merging this PR, please go through the following …
> MODINVOICE-89: Disallow "deleted" acq units from being assigned to invoices

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
> MODINVOICE-115 FOLIO-2358 manage container memory

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
[MODINVOICE-120](https://issues.folio.org/browse/MODINVOICE-120) - Voucher "accounting code" not set
The voucher should be assigned an accounting code from the invoice. Currently it is given a temporary code.
The voucher is assigned an accounting code from the invoice
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> MODINVOICE-120 - Voucher "accounting code" not set

- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigHelper.java
- src/test/java/org/folio/rest/impl/MockServer.java
It was discovered during testing that there's an issue with GET export-configurations by query.  More specifically, the query arguments were mangled when forming the storage url to call.
e.g. `?query=batchGroupId==XYZ` resulted in `?limit=10&offset=0batchGroupId==XYZ`
For reference:  [MODINVOICE-128](https://issues.folio.org/browse/MODINVOICE-128)
* Use `HelperUtils.getEndpointWithQuery(...)`
* Update unit tests to cover this case …
> MODINVOICE-128 - fixing get by query

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-147](https://issues.folio.org/browse/MODINVOICE-147) - Invoice approval fails if a voucherNumberPrefix isn't configured
It was determined that this is the result of a NullPointerException in InvoiceHandler.
null-check for prefix …
> MODINVOICE-147 - Invoice approval fails if a voucherNumberPrefix isn't configured

- src/main/java/org/folio/rest/impl/InvoicesImpl.java
Follow up commit to [PR#125](https://github.com/folio-org/mod-invoice/pull/125) for limit document size decreasing to 5 Mb. Verified locally invoice API Tests (3 iterations) + 5 Mb request (300 iterations) with heap 256Mb:
> MODINVOICE-124

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/adjusment/AdjustmentsService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-199](https://issues.folio.org/browse/MODINVOICE-199)
- update invoice lines status after invoice status transitions is finished
- removed invoceLines cache, as now lines will be retrieved only once
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODINVOICE-199 Invoice line status is not updated

- pom.xml
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/services/expence/ExpenseClassRetrieveService.java
- src/main/java/org/folio/services/finance/BudgetExpenseClassService.java
- src/main/java/org/folio/services/transaction/PaymentCreditWorkflowService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/rest/core/RestClientTest.java
- src/test/java/org/folio/services/expense/ExpenseClassRetrieveServiceTest.java
- src/test/java/org/folio/services/finance/BudgetExpenseClassTest.java
- src/test/java/org/folio/services/finance/BudgetValidationServiceTest.java
- src/test/java/org/folio/services/finance/CurrentFiscalYearServiceTest.java
- src/test/java/org/folio/services/transaction/BaseTransactionServiceTest.java
- src/test/java/org/folio/services/transaction/PendingPaymentWorkflowServiceTest.java
- src/test/java/org/folio/services/voucher/UploadBatchVoucherExportServiceTest.java
[MODINVOICE-205](https://issues.folio.org/browse/MODINVOICE-205)
UI requires fundCode and expenseClass name instead of UUIDs in error's parameters …
> MODINVOICE-205 Error must be returned in case of budget expense class mismatch

- pom.xml
it is necessary to update dependency on data-import-processing-core library to pick up fix for EDIFACT records data retrieving
[MODSOURMAN-527](https://issues.folio.org/browse/MODSOURMAN-527)
> MODSOURMAN-527 - Update dependency on processing-core library

- pom.xml
- src/main/java/org/folio/config/KafkaConsumersConfiguration.java
When attempting to import a file the import job does not complete due to the following error
org.apache.kafka.common.errors.RecordTooLargeException: The message is 1287037 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
Update to folio-kafka-wrapper v2.3.2 allows to set max.request.size parameter
https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_max.request.size
> MODINVOICE-282 Support max.request.size configuration

- pom.xml
When attempting to import file the import job is completed with errors.
To fix invoice import on the hosted envs, it is necessary to update the data-import-processing-core library version
> MODDATAIMP-516 - EDIFACT invoice does not import

- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
Fix a problem with encumbrances not being released for POL if invoice line created for that POL was edited to use different funds even if invoice that is being approved is set to release encumbrances.
- When approving invoice search every POL for encumbrances that don't have same fund ID and POL ID as any of encumbrances in the invoice lines.
- Release such encumbrances.
- Do PRs exist …
> MODINVOICE-290 - Release old POL encumbrances even if invoice line has changed funds

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/dataimport/cache/CacheLoadingException.java
- src/main/java/org/folio/dataimport/cache/JobProfileSnapshotCache.java
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/main/java/org/folio/dataimport/handlers/events/DataImportKafkaHandler.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/dataimport/cache/JobProfileSnapshotCacheTest.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/verticles/DataImportConsumerVerticleTest.java
to reduce event payload size by removing jobProfileSnapshot
* fetch jobProfileSnapshot on demand and cache it for subsequent usage
* remove all zipping/unzipping operations for data-import payload
* update tests
[MODINVOICE-259](https://issues.folio.org/browse/MODINVOICE-259)
should be merged after https://github.com/folio-org/data-import-processing-core/pull/166
> MODINVOICE-251 - Remove zipping mechanism for data import event payloads and use cache for params

- pom.xml
folio-kafka-wrapper v2.4.0 was released, the development version 2.4.0-SNAPSHOT is no longer relevant and will be deleted from nexus repository
> Update folio-kafka-wrapper to 2.4.0

- NEWS.md
- pom.xml
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/main/java/org/folio/dataimport/handlers/events/DataImportKafkaHandler.java
- src/main/java/org/folio/dataimport/utils/DataImportUtils.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
- src/test/java/org/folio/dataimport/utils/DataImportUtilsTest.java
https://issues.folio.org/browse/MODINVOICE-306
To resolve this issue it was necessary changes in 3 modules:
- Need to add necessary permission in mod-data-import. Corresponding PR: https://github.com/folio-org/mod-data-import/pull/198
- Current PR in mod-invoice, in scope of each it was necessary to change logic for retrieving Okapi permissions, because without these changes recently added desired permission in mod-data-import is not visible for mod-invoice processing. Also it was fixed issue connected with calling acquisition-units endpoint when providing language as null
- Its needed changes in data-import-processing-core. Corresponding PR was merged: https://github.com/folio-org/data-import-processing-core/pull/176/files. The issue connected with invoice mapping in …
> MODINVOICE-306. Acq unit in invoice field mapping profile causes import to complete with errors

- pom.xml
update di-core library version to provide support of mapping syntax for multiple EDIFACT fields for invoice mapping.
[MODDICORE-199](https://issues.folio.org/browse/MODDICORE-199)
> MODDICORE-199 - Add EDIFACT mapping syntax for multiple fields mapping into 1 invoice field

- NEWS.md
- pom.xml
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
At the original issue configuration MAX_REQUEST_FILE on SRM was 4mb, on SRS 4mb, on mod-invoice 1mb.
File that was mentioned in issue successfully processed, all invoice lines created, but during sending DI_COMPLETE RecordTooLargeException occured.
During investigation it was found that most of size allocated for parsed record object(not invoice lines object) and it is optional for sending back to SRM, but removing this property allows to reduсe payload in 6 times (comparing with size of invoice lines object)
Get parsed record size: 1,241,626 bytes
Get raw record size: 159,021 bytes
Invoice lines size: 233,288 bytes
> MODINVOICE-356. Fix progress bar stuck behaviour after the RecordTooLargeException

- src/main/java/org/folio/config/KafkaConsumersConfiguration.java
Even though Kafka message payload was significantly decreased, it is still recommended to adjust MAX_REQUEST_SIZE value to allow importing large files. Setting default value to 4000000 bytes would make adjustment of that property unnecessary.
> Adjust default max_request_size value for kafka messages

- src/main/java/org/folio/invoices/utils/InvoiceLineProtectedFields.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
[MODINVOICE-328](https://issues.folio.org/browse/MODINVOICE-328) - Allow editing of subscription dates after an invoice is paid
- Removed the fields from InvoiceLineProtectedFields
- Updated test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> [MODINVOICE-328] Removed subscription dates and info from protected fields

- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/services/finance/budget/BudgetService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/services/finance/budget/BudgetExpenseClassTest.java
- src/test/java/org/folio/services/finance/budget/BudgetServiceTest.java
[MODINVOICE-463](https://issues.folio.org/browse/MODINVOICE-463) - Provide fiscalYear field for pending payments, payments and credits
- When defined, use the invoice fiscal year id to retrieve the budgets for processing approve&pay. The budgets' fiscal year is already used to create transactions.
- Updated unit tests
- Fixed indents
See [related integration test](https://github.com/folio-org/folio-integration-tests/pull/928).
Right now the fiscal year must be given in the invoice before creating the lines, otherwise there could be an error if a current budget is missing for a fund that has a budget in the past fiscal year we want to use. There are similar issues with expense classes. We will have to either change the checks, or provide the invoice fiscal year earlier in the process. …
> [MODINVOICE-463] Using invoice FY to find budgets to approve/pay

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/services/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/services/finance/transaction/EncumbranceServiceTest.java
[MODINVOICE-474](https://issues.folio.org/browse/MODINVOICE-474) - Update the encumbrance when using a past fiscal year
- When an invoice line is created based on an order line, update encumbrance links if needed to make sure they use encumbrances in the invoice fiscal year; remove the links when there is no matching encumbrance; avoid getting the encumbrances if updates are not needed (when all encumbrances match the invoice fiscal year)
- When an invoice fiscal year is changed, update the links similarly to make sure they only point to encumbrances in the invoice fiscal year
- Reused some existing code used during approval to update encumbrance links
- Take expense classes into account when matching holders and retrieved encumbrances (this was not done previously, during invoice …
> [MODINVOICE-474] Update encumbrance links with fiscal year

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODINVOICE-501
Permissions: invoice.item.approve, invoice.item.pay are used in UI but not created in module descriptor.
In this PR we are declaring them in module descriptor and they will be automatically created
> [MODINVOICE-501] Create necessary missed permissions that used in UI

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/services/order/OrderLineService.java
- src/main/java/org/folio/utils/ExceptionUtil.java
- src/test/java/org/folio/services/order/OrderServiceTest.java
https://issues.folio.org/browse/MODINVOICE-514
Check if error from mod-orders matches the corresponding pattern and return different custom error.
especially as the number of …
> [MODINVOICE-514] - Uninformative error in invoice payment due to usernot linked to the Purchase Order's acquisition unit

- NEWS.md
- pom.xml
- src/main/java/org/folio/verticles/DataImportConsumerVerticle.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
- src/test/java/org/folio/verticles/DataImportConsumerVerticleTest.java
Remove initial saving of records in SRS
[MODDATAIMP-957](https://issues.folio.org/browse/MODDATAIMP-957)
especially as the number of inter-module and inter-team dependencies …
> MODDATAIMP-957: remove initial saving of records in SRS

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODINVOICE-532 - Missing interface dependencies in module descriptor
> MODINVOICE-532. Missing interface dependencies in module descriptor

- src/main/java/org/folio/services/order/OrderLineService.java
- src/test/java/org/folio/services/order/OrderServiceTest.java
https://folio-org.atlassian.net/browse/MODINVOICE-534
Rethrow `userNotAMemberOfTheAcq` in the same way as it was done in scope of https://folio-org.atlassian.net/browse/MODINVOICE-514
Communication is paramount if that is to be …
> [MODINVOICE-534] - Rethrow user not linked order's acquisition unit error

- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
[MODINVOICE-540](https://folio-org.atlassian.net/browse/MODINVOICE-540) - Mod-invoice tries to release encumbrances that are already released
Filter the encumbrances by encumbrance status before releasing them.
Communication is …
> [MODINVOICE-540] Do not try to release released encumbrances

- descriptors/ModuleDescriptor-template.json
When updating voucher we also updating voucher number in the corresponding invoice. To do this update we firstly getting invoice by id and updating that invoice with new voucher number.
So 2 module permissions are added, related issue - https://folio-org.atlassian.net/browse/MODINVOICE-542
> MODINVOSTO-172. Add missed module permissions

- src/main/java/org/folio/services/invoice/InvoicePaymentService.java
- src/test/java/org/folio/services/invoice/InvoicePaymentServiceTest.java
- src/test/resources/mockdata/compositeOrders/443bcf4c-41e9-4a07-8e70-dcc71ca56069.json
- src/test/resources/mockdata/compositeOrders/e9496a5c-84d1-4f95-89ad-a764be51ca29.json
[[MODINVOICE-544] POL payment status "Payment not required" is changed to "Fully paid" after invoice was paid](<https://folio-org.atlassian.net/browse/MODINVOICE-544?atlOrigin=eyJpIjoiYzZkYmFmMDFlYjVjNGFlYWFlNjRhNzY2OTE1MTFiZmIiLCJwIjoiaiJ9>)
- Add ignore **Payment Not Required** during payment status update
- Applied for both invoice payment and invoice cancellation
> [MODINVOICE-544]. Add ignore order line payment status, add tests

- src/main/java/org/folio/services/validator/FundAvailabilityHolderValidator.java
- src/test/java/org/folio/services/validator/FundAvailabilityHolderValidatorTest.java
https://folio-org.atlassian.net/browse/MODINVOICE-547
Changed calculation 
replace: [remaining amount] = (allocated + netTransfers) * allowableExpenditure - (awaitingPayment + expended)
by: [remaining amount] = (allocated + netTransfers) * allowableExpenditure - (awaitingPayment + expended - credited)
> [MODINVOICE-547] - Separate credits from expenditures in mod-invoice

- descriptors/ModuleDescriptor-template.json
Method GetCurrentFiscalYear is used in validation for both POST and PUT invoice. Module permission declaration for POST invoice was missed.
> Add missed fiscal year permission for POST invoice

- pom.xml
https://folio-org.atlassian.net/browse/MODINVOICE-552
Upgrade Vert.x from 4.5.4 to 4.5.9.
This indirectly upgrades Netty from 4.1.107.Final to 4.1.111.Final fixing Allocation of Resources Without Limits or Throttling:
* https://security.snyk.io/package/maven/io.netty:netty-codec-http/4.1.107.Final
Upgrade Apache SSHD/SFTP from 2.8.0/2.9.0 to 2.13.2 fixing vulnerabilities:
* https://security.snyk.io/package/maven/org.apache.sshd:sshd-common/2.9.0
* https://security.snyk.io/package/maven/org.apache.sshd:sshd-core/2.9.0
* https://security.snyk.io/package/maven/org.apache.sshd:sshd-sftp/2.9.0
To avoid diverging versions use dependencyManagement for vertx and testcontainers.
Fix vulnerabilities.
Upgrade Vert.x and sshd/sftp dependencies.
Before merging this PR, please go through the following …
> MODINVOICE-552: Vert.x 4.5.9, Netty 4.1.111, Apache sshd/sftp 2.13.2

- src/main/java/org/folio/services/invoice/InvoicePaymentService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-555>
- Perform partial code revert
- Address `CompletableFuture.join()` deprecation (https://vertx.io/docs/apidocs/io/vertx/core/CompositeFuture.html#join-io.vertx.core.Future-io.vertx.core.Future)
- Tested against existing mod-invoice and cross-module Karate tests
- <https://github.com/folio-org/mod-invoice/pull/405>
> [MODINVOICE-555]. Order line status NOT updated when paying against previous Fiscal Year

- src/main/java/org/folio/services/adjusment/AdjustmentsService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesProratedAdjustmentsTest.java
- src/test/java/org/folio/rest/impl/InvoicesProratedAdjustmentsTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-554>
- Add a custom method for correct invoice lines-independent VAT calculation 
- Calculate invoice line adjustment amount with `adjustmentAmount = (adjustmentRate * 100) / (100 + adjustmentRate)`
- Calculate invoice line sub total amount with `subTotal = subTotal - adjustmentAmount`
- Tested with unit tests and Karate tests for regression
> [MODINVOICE-554]. Invoices app: Incorrect formula for calculating adjustments, that are included and pro-rated by amount

- pom.xml
data-import-processing-core was released and snapshot version does not exist any more. Need to switch to released version to avoid failing builds.
> Update data-import-processing-core to released version

- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/rest/impl/MockServer.java
https://folio-org.atlassian.net/browse/MODINVOICE-566
After upgrading to new version RMB this issue become occurring:
It is because there is note in https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-353
`Don't use JsonObject.mapFrom to serialize a Java class instance to JSON, RMB's database methods take a Java class and automatically serialize it. When writing custom SQL use ObjectMapperTool.valueAsString to serialize in a way compatible with RMB's deserializer.`
After the fix:
> MODINVOICE-566. Error When Run Batch Voucher Export Manually

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/dataimport/utils/DataImportUtils.java
* [MODINVOICE-568](https://issues.folio.org/browse/MODINVOICE-568) Use system user for handling DI events
To support DI operation in Eureka, we should implement support for performing asynchronous operations on behalf of a system user. 
Add system user to handle data-import events with null or empty token
> MODINVOICE-568 Use system user during data-import invoice creation

- .gitignore
- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
- src/main/java/org/folio/services/invoice/InvoiceApprovalService.java
- src/test/java/org/folio/services/finance/transaction/BaseTransactionServiceTest.java
- src/test/java/org/folio/services/finance/transaction/PendingPaymentWorkflowServiceTest.java
[MODINVOICE-519](https://folio-org.atlassian.net/browse/MODINVOICE-519) - Rollback pending payment creation if an error occurs during approval
- When approving an invoice, catch errors happening after the pending payments have been created.
- In this case, rollback the creation of the pending payments by deleting them.
- Also rollback the release of encumbrances, by using the old encumbrances stored in the holders and comparing them to newly retrieved encumbrances; the encumbrances that have been released are unreleased.
- Rethrow the initial error
- New unit test checking the rollbacks
- Also added `postgres-conf.json` to `.gitignore`
Note: there is no integration test for this ticket; if there was an error after creating pending payments we would have to fix it and the test wouldn't …
> Rollback pending payment creation if an error occurs during approval

- src/main/resources/javamoney.properties
- <https://folio-org.atlassian.net/browse/MODINVOICE-579>
- Fully disable Java Money Moneta's inbuilt external providers by setting `urls` to empty string and `type` set to **NEVER**
- Add an `IDENT` provider back to the chain to avoid silent exceptions on service startup
> [MODINVOICE-579-2]. Fully disable Java Money Moneta's inbuilt external providers

- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/services/order/OrderLineService.java
- src/main/java/org/folio/services/order/OrderService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
- src/test/java/org/folio/services/order/OrderLineServiceTest.java
- src/test/java/org/folio/services/order/OrderServiceTest.java
- src/test/resources/mockdata/compositeOrders/0cb6741d-4a00-47e5-a902-5678eb24478d.json
- src/test/resources/mockdata/compositeOrders/201a7028-df56-11eb-ba80-0242ac130004.json
- src/test/resources/mockdata/compositeOrders/443bcf4c-41e9-4a07-8e70-dcc71ca56069.json
- src/test/resources/mockdata/compositeOrders/e9496a5c-84d1-4f95-89ad-a764be51ca29.json
- src/test/resources/mockdata/poLines/0000edd1-b463-41ba-bf64-1b1d9f9d0001.json
- src/test/resources/mockdata/poLines/0000edd1-b463-41ba-bf64-1b1d9f9d0003.json
- src/test/resources/mockdata/poLines/0009662b-8b80-4001-b704-ca10971f175d.json
- src/test/resources/mockdata/poLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
[MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
- Removed alerts and reporting codes
- Use a single po line schema, no more "composite po line"
- See [mod-orders-storage](https://github.com/folio-org/mod-orders-storage/pull/477)
- Required for compilation: [acq-models](https://github.com/folio-org/acq-models/pull/520)
- Are …
> [MODORDERS-1269] Single po line schema, no sub-object
