folio-org/mod-invoice

- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-25](https://issues.folio.org/browse/MODINVOICE-25) allow to get module's json schemas to be used
- enabling /_/jsonSchemas API
- updating RMB version to 23.12.0
- removing _tenant APIs since these APIs are not necessary for this module. …
> MODINVOICE-25 Use Json API for loading module schemas

- Dockerfile
- descriptors/ModuleDescriptor-template.json
- ramls/invoice.raml
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/test/java/org/folio/rest/imp/InvoicesTest.java
- src/test/java/org/folio/rest/imp/MockServer.java
[MODINVOICE-33](https://issues.folio.org/browse/MODINVOICE-33) Implement `DELETE /invoice/invoices/{id}`
> MODINVOICE-33 Implement DELETE invoice

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-31](https://issues.folio.org/browse/MODINVOICE-31)Implement basic PUT /invoice/invoices/{id} …
> MODINVOICE-31 Implement PUT /invoicing/invoices/id

- descriptors/ModuleDescriptor-template.json
- ramls/invoice.raml
- ramls/voucher.raml
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
- src/test/resources/mockdata/vouchers/a9b99f8a-7100-47f2-9903-6293d44a9905.json
- src/test/resources/mockdata/vouchers/vouchers.json
https://issues.folio.org/browse/MODINVOICE-41
Adding basic implementation, add unit tests …
> MODINVOICE-41-GET /voucher/vouchers/<id>

- descriptors/ModuleDescriptor-template.json
- ramls/voucher.raml
- src/main/java/org/folio/rest/impl/VoucherLineHelper.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/VoucherLinesApiTest.java
- src/test/resources/mockdata/voucherLines/voucher_line.json
- src/test/resources/mockdata/voucherLines/voucher_lines.json
https://issues.folio.org/browse/MODINVOICE-40
- Implement PUT `/voucher/voucher-lines/<id>` by making a proxy call to `/voucher-storage/voucher-lines`
- Add unit tests
- Add permissions
- `sourceId` is required so update test resource by adding it …
> Implement PUT for /voucher/voucher-lines/<id>

- descriptors/ModuleDescriptor-template.json
- ramls/examples/errors_500.sample
- ramls/voucher.raml
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
[MODINVOICE-47](https://issues.folio.org/browse/MODINVOICE-47) Implement GET /voucher/voucher-number/start
- proxy the request to GET /voucher-storage/voucher-number/start
- create a new interface and permission for the Get voucher number API
> MODINVOICE-47 Implement GET /voucher/voucher-number/start

- descriptors/ModuleDescriptor-template.json
- ramls/voucher.raml
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
[MODINVOICE-57](https://issues.folio.org/browse/MODINVOICE-57) Implement GET /voucher/vouchers
- proxy the request to GET /voucher-storage/vouchers
- Update existing interface and permission for the GET vouchers API
> MODINVOICE-57: Implement GET /voucher/vouchers

- descriptors/ModuleDescriptor-template.json
[MODORDERS-258](https://issues.folio.org/browse/MODORDERS-258) Create 6.0 mod-orders release
Update dependency to 6.0
> MODORDERS-258 Create MODORDERS release

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/InvoiceLineProtectedFields.java
- src/main/java/org/folio/invoices/utils/InvoiceProtectedFields.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VoucherLineHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-46](https://issues.folio.org/browse/MODINVOICE-46) voucherNumbers should be generated based on the configured prefix and sequence
- Refactored the getting configuration logic as follows 
- replaced `ConfigurationsClient.getConfigurationsEntries()` by `HelperUtils.handleGetRequest()` to be able reuse and close `httpClient`
- load configuration from the beginning and store in `AbstractHelper.tenantConfiguration` variable
- get the required configuration from this variable when needed
- updating voucherNumber generation logic to concatenate sequence number with extracted from mod-configuration voucher number prefix if present and valid
- returning error response with appropriate error code
Additionally added to enums missing invoice and invoiceLine protected fields
Before merging …
> MODINVOICE-46 voucherNumber Generation

- pom.xml
[MODINVOICE-36](https://issues.folio.org/browse/MODINVOICE-36) After module deployment, no `ExchangeRateProvider `is available other than `IdentityRateProvider` (which provides exchange rate with factor only for identical base/term currencies)
- adding `ServicesResourceTransformer` and `AppendingTransformer`  transformers  to maven-shade-plugin
https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer
https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#AppendingTransformer
If there are breaking changes, …
> MODINVOICE-34 Create voucher on transition to "Approved"

- src/test/resources/mockdata/poLines/0009662b-8b80-4001-b704-ca10971f175d.json
- src/test/resources/mockdata/poLines/2bafc9e1-9dd3-4ede-9f23-c4a03f8bb2d5.json
- src/test/resources/mockdata/poLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
https://issues.folio.org/browse/MODORDERS-275 - Make poLine.source an enum
Change to use source enum changes
Change mock data
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODORDERS-275- Change Source to enum

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-80](https://issues.folio.org/browse/MODINVOICE-80) Create MODINVOICE release
- updating NEWS.md
- versions of required interfaces …
> MODINVOICE-80 - Release 1.0.0

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/resources/mockdata/invoices/52fd6ec7-ddc3-4c53-bc26-2779afc27136.json
- src/test/resources/mockdata/invoices/invoices.json
https://issues.folio.org/browse/MODINVOICE-74
* Assigned acqusition units from invoice to voucher upon voucher creation
* Updated unit tests …
> MODINVOICE-74 assigned acq units from invoice to voucher

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/voucher.raml
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/VoucherLinesApiTest.java
https://issues.folio.org/browse/MODINVOICE-90
* Updated raml
* Updated module descriptor
* Method GET GET /voucher/voucher-lines implemented
* Unit tests created
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODINVOICE-90 implemented GET /voucher/voucher-lines endpoint

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/ProtectedOperationType.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/DocumentHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/impl/ProtectionHelper.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VoucherLineHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/protection/InvoicesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/ProtectedEntityTestBase.java
- src/test/java/org/folio/rest/impl/protection/ProtectedOperations.java
- src/test/resources/mockdata/acquisitionUnits/memberships.json
- src/test/resources/mockdata/acquisitionUnits/units.json
- src/test/resources/mockdata/invoices/52fd6ec7-ddc3-4c53-bc26-2779afc27136.json
- src/test/resources/mockdata/invoices/invoices.json
[MODINVOICE-72](https://issues.folio.org/browse/MODINVOICE-72) Restrict  search/view of invoice, invoiceLine records based upon acquisitions unit
The same approach as for mod-orders,  the only difference is that to search for invoice lines  "invoices.acqUnitIds" parameter is used instead of "acqUnitIds".
Ideally all of the PRs involved in breaking …
> MODINVOICE-72 Restrict search/view of invoice, invoiceLine records based upon acquisitions unit

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODINVOICE-69
- Add missing permission for restrict creation of invoice, invoiceLine records based upon acquisitions unit
- Add permission in module descriptor - `invoices.acquisitions-units-assignments.assign` …
> Add missing permissions for MODINVOICE-69

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/MockServer.java
https://issues.folio.org/browse/MODINVOICE-91
Naming mismatch was found during integration with UI
* Fixed configuration names
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODINVOICE-91 fixed naming mismatch

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/resources/mockdata/fundRecords/fundsCollection.json
[MODFISTO-19](https://issues.folio.org/browse/MODFISTO-19) 
Since the `externalAccountNo` is no longer a required field, added a check to make sure that the fund contains the `externalAccountNo` when the invoice is `Approved`, otherwise the corresponding error is returned.
Ideally all of the PRs involved in breaking changes would be merged in the same …
> MODFISTO-19 Update fund schema

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-71](https://issues.folio.org/browse/MODINVOICE-71 )
Add missing `invoice-storage.invoices.collection.get` permission in delete invoice-line by id
- Update module descriptor to add missing permission
- Fix `IndexOutOfBoundsException` if it tries to delete a nonexistent invoice line
Ideally all of the PRs involved in breaking changes would be …
> Invoice-line missing permission

- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
[MODINVOICE-96](https://issues.folio.org/browse/MODINVOICE-96)
- replacing Fund and FundCollection models by JsonObject …
> MODINVOICE-96 Add support for latest and v3.0.0 mod-finance-storage versions

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/invoice.raml
- ramls/voucher.raml
- src/main/resources/log4j2.properties
[MODINVOICE-92](https://issues.folio.org/browse/MODINVOICE-92) Release 2.0.0
- Updating News.md
- Updating interface version
- Adding acquisitions-units 1.1 to required
Interface | Version | Reason for change
------------ | ------------- | -------------
`invoice` | 2.0 | [MODINVOICE-77](https://issues.folio.org/browse/MODINVOICE-77) as breaking change
`voucher` | 1.1 | [MODINVOSTO-31](https://issues.folio.org/browse/MODINVOSTO-31) …
> MODINVOICE-92 - Release 2.0.0

- pom.xml
- src/main/java/org/folio/invoices/utils/HelperUtils.java
[MODORDSTOR-108](https://issues.folio.org/browse/MODORDSTOR-108) Add qualifier field to `poLine->details->productIds[]`
Updating the acq-models
> MODORDSTOR-108 Add qualifier field

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/InvoiceLinesProratedAdjustmentsTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesProratedAdjustmentsTest.java
https://issues.folio.org/browse/MODINVOICE-103
- If there are no invoice lines then adjustmentsTotal = sum of all invoice adjustments
- If lines are present then adjustmentsTotal = notProratedInvoiceAdjustments + sum of invoiceLines adjustmentsTotal
- Update unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> MODINVOICE-103 Adjustment Total Calculation is wrong

- pom.xml
- src/main/java/org/folio/rest/impl/InitEventBus.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-97](https://issues.folio.org/browse/MODINVOICE-97) nvoice should be allowed to transition to "Paid" if it has an invoice line with an empty "poLineId" field.
- updated payment logic to allow pay for invoice with lines w/o poLineId
- added test for updated logic
- updated RMB to the latest version
Ideally all of the PRs involved in breaking …
> MODINVOICE-97 Can not pay the invoice

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
https://issues.folio.org/browse/MODINVOICE-84
* mod-finance is called instead of mod-finance-storage 
* Fund model is used instead of plain json object
* interface dependencies are updated
* module permissions are updated.
* RMB updated to v29.0.1 …
> MODINVOICE-84 use finance business logic module

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Release mod-invoice-3.0.0
- new updated
- invoice minor version increased, only minor changes since the latest breaking changes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODINVOICE-62 - Release 3.0.0

- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/resources/javamoney.properties
[MODINVOICE-122](https://issues.folio.org/browse/MODINVOICE-122) - nvestigate OOM issues on mod-invoice
The app crashing on testing and snapshot environment due to OOM/high memory utilization.
Making currency provider configurable - allow only ECB currency provider.
**It can be useful to consider heap memory increasing for mod-invoice because of memory high but stable utilization. Memory usage during 4 hours testing with different scenarious for invoices doesn't increase that means lack of memory leaks.**
- What other modules …
> MODINVOICE-122 - Investigate OOM issues on mod-invoice

- descriptors/ModuleDescriptor-template.json
- src/test/resources/mockdata/poLines/0009662b-8b80-4001-b704-ca10971f175d.json
- src/test/resources/mockdata/poLines/2bafc9e1-9dd3-4ede-9f23-c4a03f8bb2d5.json
- src/test/resources/mockdata/poLines/c2755a78-2f8d-47d0-a218-059a9b7391b4.json
Handle breaking changes in [MODORDERS-349](https://issues.folio.org/browse/MODORDERS-349)
- updating acq-models
- replace orders-8.0 interface by order-lines-1.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODORDERS-349 Make title schema changes to all APIs

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODINVOICE-118
increase container memory / heap by 256M …
> MODINVOICE-118 mod-invoice was out-of-memory killed on folio-snapshot-demo system

- ramls/schemas/batch_voucher.xsd
Bug fixing of [MODINVOSTO-126 origin PR](https://github.com/folio-org/mod-invoice/pull/98)
Make **fundCodes** required …
> [MODINVOSTO-126] - XML schema for batch-voucher

- descriptors/ModuleDescriptor-template.json
- ramls/schemas/batch_voucher.xsd
- ramls/voucher.raml
- src/main/java/org/folio/invoices/utils/VoucherProtectedFields.java
- src/main/java/org/folio/rest/impl/VoucherHelper.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/test/java/org/folio/rest/impl/VouchersApiTest.java
[MODINVOICE-139](https://issues.folio.org/browse/MODINVOICE-139) - Create PUT /voucher/vouchers/<id>
We need to be able to edit a few parts of the voucher after it's been generated. The fields that should be editable are:
- voucher.dispersementNumber
- voucher.dispersementDate
- voucher.dispersementAmount
- voucher.voucherNumber
Attempting to edit any other fields should result in an appropriate error.
- API is defined and implemented (RAML/ModDesc/Code)
- Unit tests are updated …
> MODINVOICE-139 - Create PUT /voucher/vouchers/{id}

- descriptors/ModuleDescriptor-template.json
- ramls/batch-voucher-export-configuration.raml
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherImpl.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/BatchVoucherExportConfigCredentialsTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/credentials/574f0791-beca-4470-8037-050660cfb73a.json
[MODINVOICE 129](https://issues.folio.org/browse/MODINVOICE-129) Define and implement the batch-voucher.configurations.credentials API
* API is defined and implemented (RAML/ModDesc/code)
* unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODINVOICE 129 - Create credentials API

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODFIN-113 ](https://issues.folio.org/browse/MODFIN-113) acq-models submodule in mod-invoice has to be updated
- set invoiceId and invoiceLineId field in the awaitingPaymet upon invoice approval
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> MODFIN-113 Add invoiceId and invoiceLineId to the awaitingPayment schema

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
Follow-up PR to [#92](https://github.com/folio-org/mod-finance-storage/pull/92) for fixing issue with voucher number prefix NPE.
> MODFISTO-91 - Budgets aren't updated correctly upon updating/releasing encumbrance

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/invoice.raml
- ramls/voucher.raml
[MODINVOICE-143](https://issues.folio.org/browse/MODINVOICE-143) release mod-invoice
new interfaces introduced:
- batch-voucher.batch-vouchers 1.0
- batch-group 1.0
- batch-voucher.batch-vouchers 1.0
increased minor version of:
- invoice 3.2 -> 3.3  (new field batchGroupId in invoice schema, logic to call awaiting payment API upon approval)
- voucher-storage.vouchers 2.0 -> 2.1  (new field batchGroupId in invoice - required, with default value)
- Do JIRAs exist to update the …
> MODINVOICE-143 release 3.1.0

- descriptors/ModuleDescriptor-template.json
- ramls/batch-voucher-exports.raml
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportsHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportsImpl.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/BatchVoucherExportsApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/batchVoucherExports/566c9156-e52f-4597-9fee-5ddac91d14f2.json
- src/test/resources/mockdata/batchVoucherExports/batch_voucher_exports_collection.json
https://issues.folio.org/browse/MODINVOICE-131
- Define APIs by proxying to the storage module
- Stub out `upload` and `scheduled` endpoints
- Update RAML, Module descriptor
- Unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> MODINVOICE-131 Create batch-voucher-export CRUD API

- pom.xml
- src/main/java/org/folio/exceptions/FtpException.java
- src/main/java/org/folio/invoices/utils/FtpUploadHelper.java
- src/main/java/org/folio/invoices/utils/UploadHelper.java
- src/main/java/org/folio/invoices/utils/UploadHelperFactory.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherImpl.java
- src/test/java/org/folio/invoices/util/FtpUploadHelperTest.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/BatchVoucherExportConfigCredentialsTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/batchVoucherExportConfigs/badb333c-503f-4627-895d-26eaab1e392e.json
- src/test/resources/mockdata/credentials/574f0791-beca-4470-8037-050660cfb73a.json
- src/test/resources/mockdata/credentials/badf0791-beca-4470-8037-050660cfb73a.json
See [MODINVOICE-137](https://issues.folio.org/browse/MODINVOICE-137)
* Use [apache-commons-net](https://commons.apache.org/proper/commons-net/) for ftp client
* Use [mockftpserver ](http://mockftpserver.sourceforge.net/) for unit testing
* Create an UploadHelper interface and Factory
* Create an FtpUploadHelper (Implements UploadHelper )
* Later we can add additional impls for SFTP, etc.
NOTE: I started this work a while ago and had originally forgot that the FtpHelperUtil and related unit test include upload functionality.  I thought it made more sense to keep it than remove it, even though this code is currently unreachable from an API. …
> MODINVOICE-137 - implement ftp "test" endpoint

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-109](https://issues.folio.org/browse/MODINVOICE-109) - Create payment or credit when Invoice marked as 'Paid'
When an invoice is processed payments or credits need to be created again the Funds that are responsible for accounting for the invoices value.
1. Determine the expected number of payments & credits. (done in scope of https://issues.folio.org/browse/MODINVOICE-113)
2. Check if the payments have already been processed. If yes, go to step 5
use GET /finance/transactions?query=invoiceInvoiceId==<invoiceId>.
3. Create payment_summary
Use POST /finance/invoice-payment-summaries (done in scope of https://issues.folio.org/browse/MODINVOICE-113)
4. Generate and send payments & credits for processing
- get current fiscalYear by `fundId`
- get system currency to populate …
> MODINVOICE-109 - Create payment or credit when Invoice marked as 'Paid'

- src/main/java/org/folio/rest/impl/FinanceHelper.java
Fllow-on work to [MODINVOICE-109](https://issues.folio.org/browse/MODINVOICE-109)
The invoice is paid without creating payments or credits if there are encumbrances  with the sourceInvoiceId of the given invoice.
- fixing query for searching for processed transactions
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> MODINVOICE-109 Create payment or credit when Invoice marked as 'Paid'

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigHelper.java
Some module permissions were missed https://github.com/folio-org/mod-invoice/pull/110#discussion_r396506883 …
> MODINVOICE-137 Implement "test" endpoint

- descriptors/ModuleDescriptor-template.json
- ramls/batch-group.raml
- ramls/batch-voucher-export-configuration.raml
- ramls/batch-voucher-exports.raml
- ramls/batch-voucher.raml
- ramls/invoice.raml
- ramls/voucher.raml
- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportsImpl.java
All Acquisition's business-modules can return errors in JSON format. So to avoid duplication we need a single place to store resource types supporting JSON-response.
Next items has been updated to return application/json for errors
- batch-group.raml
- batch-voucher.raml
- batch-voucher-export-configuration.raml
- batch-voucher-exports.raml
- invoice.raml
- voucher.raml
- BatchVoucherExportsImpl.java
- Are the JIRAs under active …
> Modinvoice 100

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/batch-group.raml
- ramls/batch-voucher-export-configuration.raml
- ramls/batch-voucher.raml
- ramls/invoice.raml
- ramls/voucher.raml
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
[MODINVOICE-150] Create Bugfix Release 3.1.1
> [MODINVOICE-150] Create Bugfix Release 3.1.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/batch-group.raml
- ramls/batch-voucher-export-configuration.raml
- ramls/batch-voucher.raml
- ramls/invoice.raml
- ramls/voucher.raml
Update version in Master according to bugfix release 3.1.1, which was released from b3.1 branch
> Update version in Master to bugfix release 3.1.1

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/resources/mockdata/invoices/c0d08448-347b-418a-8c2f-5fb50248d67e.json
https://issues.folio.org/browse/MODINVOICE-155
* added transactions creation for invoice level fundDistributions …
> MODINVOICE-155 Create payments for invoice level fundDistributions

- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-136](https://issues.folio.org/browse/MODINVOICE-136) Voucher Line's fundDistibution have to be an Amount type and converted to System currency
- convert all voucherLine.fundDistributions to amount type
- convert all voucherLine.fundDistributions value from invoice to system currency
Ideally all of the PRs involved in breaking changes would be …
> MODINVOICE-136 Evaluate fund distributions when generating voucher

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
Batch group is not transferred from invoice to voucher
Do transfer 
While it's helpful …
> [MODINVOICE-132] - Hot fix batch group id

- src/main/java/org/folio/rest/impl/VoucherHelper.java
Should be included in hotfix-release
While it's helpful for reviewers to help identify …
> [MODINVOICE-160] - Can not save voucher detail edits

- src/main/java/org/folio/converters/BatchedVoucherModelConverter.java
- src/main/java/org/folio/jaxb/JAXBUtil.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportsHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherPersisteHelper.java
- src/main/java/org/folio/services/BatchVoucherGenerateService.java
- src/test/java/org/folio/converters/BatchVoucherModelConverterTest.java
- src/test/java/org/folio/converters/BatchedVoucherModelConverterTest.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/BatchVoucherExportsApiTest.java
- src/test/java/org/folio/rest/impl/BatchVoucherExportsHelperTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/BatchVoucherGenerateServiceTest.java
MODINVOICE-161 - Fix batch voucher converting from JSON to XML
Added checks on Null for several fields  …
> [MODINVOICE-161] - Fix batch voucher converting from JSON to XML

- NEWS.md
- pom.xml
[MODINVOICE-156](https://issues.folio.org/browse/MODINVOICE-156)
Release mod-invoice-3.1.2  …
> MODINVOICE-156 MODINVOICE-3.1.2 Hotfix release

- src/main/java/org/folio/services/ftp/FtpUploadService.java
- src/main/java/org/folio/services/voucher/UploadBatchVoucherExportService.java
[MODORDSTOR-133](https://issues.folio.org/browse/MODORDSTOR-133) implement batch voucher upload logic
Fix issue with folder creation …
> [MODINVOICE-133] - Implement the "upload" endpoint

- pom.xml
- src/main/java/org/folio/converters/BatchVoucherModelConverter.java
[MODINVOICE-167](https://issues.folio.org/browse/MODINVOICE-167) - Update to RMB v30.0.1
Update to RMB v30.0.1
RMB and VertX versions updated …
> MODINVOICE-167 - Update to RMB v30.0.1

- src/main/java/org/folio/services/voucher/UploadBatchVoucherExportService.java
- src/test/java/org/folio/services/voucher/UploadBatchVoucherExportServiceTest.java
[MODORDSTOR-170](https://issues.folio.org/browse/MODORDSTOR-170) implement batch voucher upload logic
Fix issue with file name generator …
> [MODINVOICE-170] - Fix batch voucher file name generation

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-166](https://issues.folio.org/browse/MODINVOICE-166)
- news update
- update required interfaces: order-lines:1.3, batch-voucher-storage.batch-voucher-exports:1.1, organizations-storage.organizations:3.1
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> Tmp release 4.0.0

- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
https://issues.folio.org/browse/MODINVOICE-171
* updated batched voucher mapping
While …
> MODINVOICE-171 fixed batchedVoucher creation

- src/main/java/org/folio/models/FundDistributionTransactionHolder.java
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-168](https://issues.folio.org/browse/MODINVOICE-168)
- logic has been updated to populate fundDistribution.code from fund.code
- unit tests updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODINVOICE-168 Populate field "voucherLine.fundDistribution.code" upon Invoice approval

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
https://issues.folio.org/browse/MODINVOICE-172
* added accounting code validation
While …
> MODINVOICE-172 validate accounting code

- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
[MODINVOICE-177](https://issues.folio.org/browse/MODINVOICE-177)
- updated get vouchers query to retrieve vouchers with exportToAccounting== true upon batchVoucherGeneration
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> MODINVOICE-177 Exclude vouchers with empty accountingCode from batchVoucher generation

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-173
While it's …
> release 4.0.1

- NEWS.md
https://issues.folio.org/browse/MODINVOICE-173
* update NEWS.md for master branch
While …
> MODINVOICE-173 update news.md

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/budgets/budgets.json
- src/test/resources/mockdata/fundRecords/fundsCollection.json
- src/test/resources/mockdata/ledgers/ledgers.json
[MODINVOICE-114](https://issues.folio.org/browse/MODINVOICE-114)
When an invoice is approved, we need to check that there's enough money in each of the funds. This happens before we move money from encumbered to awaiting payment.
- Verification to check enough money in budget has been added
- Tests updated
Ideally all of the PRs involved in breaking …
> [MODINVOICE-114] Check remaining amount expendable upon invoice approval

- descriptors/ModuleDescriptor-template.json
[MODFIN-131](https://issues.folio.org/browse/MODFIN-131) - Create the pending-payments API
* increased finance.transactions interface version to 4.0 …
> MODFIN-131 - Create the pending-payments API

- pom.xml
* https://issues.folio.org/browse/MODINVOSTO-71
* pointed acq-models to the lates commit …
> MODINVOSTO-71 Update fundDistribution schema

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/models/FundExtNoExpenseClassExtNoPair.java
- src/main/java/org/folio/rest/RestConstants.java
- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/rest/core/models/RequestContext.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/services/InvoiceRetrieveService.java
- src/main/java/org/folio/services/expence/ExpenseClassRetrieveService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/InvoiceRetrieveServiceTest.java
- src/test/java/org/folio/services/voucher/BatchVoucherGenerateServiceTest.java
- src/test/resources/mockdata/expense-classes/1bcc3247-99bf-4dca-9b0f-7bc51a2998c2.json
- src/test/resources/mockdata/expense-classes/expense-classes.json
- src/test/resources/mockdata/invoiceLines/invoice_lines.json
* https://issues.folio.org/browse/MODINVOSTO-174
* Change logic on invoice approval : expense classes will be added as part of external number  …
> [MODINVOICE-174] - Update transition to Approve considering the expense classes

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/rest/impl/FinanceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/resources/mockdata/budget-expense-classes/budgetExpenseClasses.json
https://issues.folio.org/browse/MODINVOICE-176
* logic updated
* updated unit tests …
> MODINVOICE-176 Prevent the creation of a transaction for an inactive expense class

- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/services/adjusment/AdjustmentsService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesProratedAdjustmentsTest.java
- src/test/java/org/folio/rest/impl/InvoicesProratedAdjustmentsTest.java
[MODINVOICE-105](https://issues.folio.org/browse/MODINVOICE-105)
Percentage prorated adjustment converted to amount type before prorate. 
Enabled prorating percentage adjustments by quantity/
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> MODINVOICE-105 Prorated Adjustments - prorating percentage adjustments

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/expence/ExpenseClassRetrieveService.java
- src/main/java/org/folio/services/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/transaction/EncumbranceService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/TestMockDataConstants.java
- src/test/java/org/folio/services/transaction/BaseTransactionServiceTest.java
- src/test/resources/mockdata/transactions/allocations.json
- src/test/resources/mockdata/transactions/credits.json
- src/test/resources/mockdata/transactions/encumbrances.json
- src/test/resources/mockdata/transactions/payments.json
- src/test/resources/mockdata/transactions/pending-payments.json
- src/test/resources/mockdata/transactions/transactions.json
- src/test/resources/mockdata/transactions/transfers.json
https://issues.folio.org/browse/MODINVOICE-182 - Link to encumbrance is missed
Link encumbrances in the invoice linens in approval invoice time.  …
> [MODINVOICE-182] - Link to encumbrance is missed

- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/rest/RestConstants.java
- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/rest/core/models/RequestContext.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/InvoiceRetrieveService.java
- src/main/java/org/folio/services/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/transaction/EncumbranceService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/TestMockDataConstants.java
- src/test/java/org/folio/rest/core/RestClientTest.java
- src/test/java/org/folio/rest/impl/ApiTestSuite.java
- src/test/java/org/folio/services/InvoiceRetrieveServiceTest.java
- src/test/java/org/folio/services/transaction/BaseTransactionServiceTest.java
- src/test/java/org/folio/services/voucher/BatchVoucherGenerateServiceTest.java
- src/test/resources/mockdata/transactions/allocations.json
- src/test/resources/mockdata/transactions/credits.json
- src/test/resources/mockdata/transactions/encumbrances.json
- src/test/resources/mockdata/transactions/payments.json
- src/test/resources/mockdata/transactions/pending-payments.json
- src/test/resources/mockdata/transactions/transactions.json
- src/test/resources/mockdata/transactions/transfers.json
> [MODINVOICE-182] - Merge to long live branch

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/test/java/org/folio/rest/core/RestClientTest.java
> [MODINVOICE-182] - Fix issue with line update

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
https://issues.folio.org/browse/MODFISTO-102
* updated acq-models …
> Modfisto 102 updated acq-models

- src/main/java/org/folio/rest/impl/BatchVoucherHelper.java
- src/main/java/org/folio/rest/impl/BatchVoucherImpl.java
- src/main/java/org/folio/services/ftp/FtpUploadService.java
- src/main/java/org/folio/services/ftp/UploadService.java
- src/main/java/org/folio/services/voucher/UploadBatchVoucherExportService.java
- src/test/java/org/folio/services/ftp/FtpUploadServiceTest.java
- src/test/java/org/folio/services/voucher/UploadBatchVoucherExportServiceTest.java
Merge changes from MODINVOICE-164
Merge changes from MODINVOICE-164
While it's helpful …
> Modinvoice 164 long

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-185
While it's …
> hotfix release 4.0.2

- src/main/java/org/folio/services/ftp/FtpUploadService.java
https://issues.folio.org/browse/MODINVOICE-193
Remove keep alive configuration and set connection timeout …
> [MODINVOICE-193] - Invoice loading stuck on Bugfest

- NEWS.md
- pom.xml
> [MODINVOICE-194] - Hotfix 4.0.3 

- src/main/java/org/folio/rest/impl/FinanceHelper.java
https://issues.folio.org/browse/MODINVOICE-198
* Expense class added to Pending payment …
> MODINVOICE-198 Expense class added to Pending payment

- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
[MODINVOICE-186](https://issues.folio.org/browse/MODINVOICE-186)
[MODINVOICE-190](https://issues.folio.org/browse/MODINVOICE-190)
updated rmb and dependencies
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODINVOICE-186/MODINVOICE-190 mod-invoice: Update RMB

- src/main/java/org/folio/models/PaymentCreditHolder.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-204](https://issues.folio.org/browse/MODINVOICE-204) …
> MODINVOICE-204 Encumbrance not linked to payments and credits upon invoice payment

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-189](https://issues.folio.org/browse/MODINVOICE-189) …
> MODINVOICE-189 - Release - 4.1.0

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/services/finance/BudgetExpenseClassService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/finance/BudgetExpenseClassTest.java
- src/test/resources/mockdata/budget-expense-classes/budgetExpenseClasses.json
- src/test/resources/mockdata/expense-classes/6e6ed3c9-d959-4c91-a436-6076fb373816.json
- src/test/resources/mockdata/expense-classes/expense-classes.json
- src/test/resources/mockdata/invoiceLines/invoice_lines.json
[MODINVOICE-205](https://issues.folio.org/browse/MODINVOICE-205)
Get budgetExpenseClass by fundId and expenseClassId 
* if nothing is found then return error response with `budgetExpenseClassNotFound` code
* if retrieved budgetExpenseClass  has inactive status return error response with `inactiveExpenseClass` code
Ideally all of the PRs involved in …
> MODINVOICE-205 Error must be returned in case of budget expense class mismatch

- pom.xml
[MODINVOICE-207](https://issues.folio.org/browse/MODINVOICE-207)
No logging in honeysuckle version
- Add fix for logging …
> [MODINVOICE-207] No logging in honeysuckle version

- pom.xml
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>
(cherry picked from commit d48e49b83022ab575c3bd1b47b74b422c85a1ba9) …
> [MODINVOICE-207] No logging in honeysuckle version (#191)

- NEWS.md
- pom.xml
> Tmp release 4.1.1

- NEWS.md
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODINVOICE-208 update news

- NEWS.md
- pom.xml
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODINVOICE-215 MODINVOICE (mod-invoice) Bugfix release

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
Fix issue with recalculation if invoice is Approved
Change calculation logic for invoice get by id …
> [MODINVOICE-213] - Fix issue with recalculation if invoice is Approved

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/test/java/org/folio/rest/impl/InvoiceHelperTest.java
Do not update payment status of Ongoing poLines > https://issues.folio.org/browse/MODINVOICE-224 …
> [MODINVOICE-224] Do not update payment status of Ongoing poLines

- descriptors/ModuleDescriptor-template.json
- src/test/resources/mockdata/invoiceLines/29846620-8fb6-4433-b84e-0b6051eb76ec.json
- src/test/resources/mockdata/invoiceLines/4051b42d-c6cf-4306-a331-209514af9877.json
- src/test/resources/mockdata/invoiceLines/55e4b6f5-f974-42da-9a77-24d4e8ef0e70.json
- src/test/resources/mockdata/invoiceLines/5cb6d270-a54c-4c38-b645-3ae7f249c606.json
- src/test/resources/mockdata/invoiceLines/b418897b-0e40-4f31-896b-9c9adc979a88.json
- src/test/resources/mockdata/invoiceLines/e0d08448-343b-118a-8c2f-4fb50248d672.json
- src/test/resources/mockdata/invoiceLines/ebd42944-20fc-4448-86ad-60ec9b73a6d7.json
- src/test/resources/mockdata/invoiceLines/invoice_lines.json
[MODORDSTOR-146](https://issues.folio.org/browse/MODORDSTOR-146)
[MODINVOSTO-81](https://issues.folio.org/browse/MODINVOSTO-81)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODINVOSTO-81/MODORDSTOR-146 Support pair of "refNumber" and "refNumberType" should be an array

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
https://issues.folio.org/browse/MODINVOICE-239
Logic updated …
> [MODINVOICE-239] - Voucher amount incorrect

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
Bugfix release 4.1.3
While it's helpful for reviewers to help identify potential …
> Bugfix release 4.1.3

- PERSONAL_DATA_DISCLOSURE.md
> [MODINVOICE-219] - Add personal data disclosure form

- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
improvement for  [MODINVOICE-231](https://issues.folio.org/browse/MODINVOICE-231)
> MODINVOICE-231 - Create invoice lines sequentially

- pom.xml
Set stable version for Kafka Wrapper
While it's helpful for reviewers to help identify …
> [MODINVOICE-216] - Fix version of the kafka wrapper

- NEWS.md
- pom.xml
> [MODINVOICE-216] - Release 5.0.0

- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/converters/AddressConverter.java
- src/main/java/org/folio/rest/impl/VoucherService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/services/voucher/BatchVoucherGenerateServiceTest.java
- src/test/resources/mockdata/organizations/one_access_providers_active.json
[MODINVOICE-240](https://issues.folio.org/browse/MODINVOICE-240)
- Included vendor address in batched vouchers.
- Used a converter for addresses because the same conversion was done in VoucherService.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> [MODINVOICE-240] Include vendor address in batched vouchers

- ramls/examples/batch_voucher_sample.xml
- ramls/schemas/batch_voucher.xsd
- src/main/java/org/folio/converters/BatchedVoucherModelConverter.java
- src/test/java/org/folio/converters/BatchedVoucherModelConverterTest.java
- src/test/resources/mockdata/batchVouchers/35657479-83b9-4760-9c39-b58dcd02ee14.json
[MODINVOICE-240](https://issues.folio.org/browse/MODINVOICE-240)
- Added vendor address to XML schema
- Updated JSON - XML converter
- Updated tests …
> [MODINVOICE-240] Added vendor address to XML schema for batched vouchers and updated converter and tests

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/FundsDistributionService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
* https://issues.folio.org/browse/MODINVOICE-245
* Split funds on a Voucher
While it's …
> MODINVOICE-245 Split funds on a Voucher with an odd number of pennies as the cost.

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-242
While it's …
> MODINVOICE-242 Release 5.0.1

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
https://issues.folio.org/browse/MODINVOICE-246
* populated invoiceLineId field
While …
> MODINVOICE-246 populated invoiceLineId field

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-247
While it's …
> MODINVOICE-247 release 5.0.2

- ramls/examples/batch_voucher_sample.xml
- ramls/schemas/batch_voucher.xsd
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/converters/AddressConverter.java
- src/main/java/org/folio/converters/BatchedVoucherModelConverter.java
- src/main/java/org/folio/rest/impl/VoucherService.java
- src/main/java/org/folio/services/order/OrderService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/converters/BatchedVoucherModelConverterTest.java
- src/test/java/org/folio/services/voucher/BatchVoucherGenerateServiceTest.java
- src/test/resources/mockdata/batchVouchers/35657479-83b9-4760-9c39-b58dcd02ee14.json
- src/test/resources/mockdata/organizations/one_access_providers_active.json
Apply fixes for BugFix 5.0.3
1. Cherry-picks MODINVOICE-240
2. Fix un issue with endpoint org.folio.services.order.OrderService#deleteOrderInvoiceRelationship(java.lang.String, org.folio.rest.core.models.RequestContext) [MODINVOICE-249]  …
> Cherry picks for 5.0.3 and MODINVOICE-249

- NEWS.md
- src/main/java/org/folio/services/order/OrderService.java
1. Update NEWS from long leave branch
2. Fix order invoice relation endpoint 
While it's …
> [MODINVOICE-249] - Fix order invoice relation endpoint

- README.md
> MODDATAIMP-431: Update module readme files to reflect Iris environment variables.

- src/main/java/org/folio/services/FundsDistributionService.java
[MODINVOICE-255](https://issues.folio.org/browse/MODINVOICE-255)
Credit transaction is given value of $0
- Rewrite odd penny logic for invoice …
> [MODINVOICE-255] Credit transaction is given value of $0

- NEWS.md
- pom.xml
- src/main/java/org/folio/services/FundsDistributionService.java
> Tmp release 5.0.4

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/main/java/org/folio/services/order/OrderService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
Relink invoice with new order if POL link was changed in invoice line > https://issues.folio.org/browse/MODINVOICE-221 …
> MODINVOICE-221 Relink invoice with new order if POL link was changed in invoice line

- pom.xml
Update folio-kafka-wrapper version to snapshot. …
> MODDPUBSUB-181: Update folio-kafka-wrapper version to 2.3.1

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/MODINVOICE-237
While it's …
> MODINVOICE-237 release 5.1.0

- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
https://issues.folio.org/browse/MODINVOICE-266
* fixed transaction processing
While it's …
> MODINVOICE-266 fixed transaction processing

- src/main/java/org/folio/services/invoice/BaseInvoiceService.java
[MODINVOICE-264](https://issues.folio.org/browse/MODINVOICE-264)
Fixed `BaseInvoiceService.recalculateInvoiceTotals(Invoice, List<InvoiceLine>)`. …
> [MODINVOICE-264] Fixed adjustmentsTotal update after a line is created

- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
[MODINVOICE-269](https://issues.folio.org/browse/MODINVOICE-269) - Invoice line is not saved when linked to POL
The code to update the order-invoice relationship was assuming that there was already a link to the POL. Adding a check that the old link exists before deleting the related relationship solves the issue.
Ideally all of the PRs involved in …
> [MODINVOICE-269] Fixed adding a link to a POL

- pom.xml
> Update data-import-processing-core dependency to v3.1.3

- src/main/java/org/folio/rest/impl/InvoiceHelper.java
https://issues.folio.org/browse/MODINVOICE-272
*fix expense classes processing
While …
> MODINVOICE-272 fix expense classes processing

- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
to fix the POL matching logic and data retrieval for invoice line
* use cross-index approach to request PO lines
[MODINVOICE-259](https://issues.folio.org/browse/MODINVOICE-259)
> MODINVOICE-259 - When EDIFACT invoice is imported, matching to PO line is not working properly

- pom.xml
https://issues.folio.org/browse/MODINVOICE-280
Added maven dependency to avoid NoClassDefFoundError when exporting vouchers. …
> MODINVOICE-280 - Fixed a problem with batch voucher export

- pom.xml
> Update data-import-processing-core dependency to v3.1.4

- src/main/java/org/folio/services/InvoiceRetrieveService.java
- src/main/java/org/folio/services/VendorRetrieveService.java
https://issues.folio.org/browse/MODINVOICE-280
1. Add distinct for toMap(Invoice::getId, Function.identity()) …
> [MODINVOICE-280] - Fix issue with stream map and identity

- NEWS.md
- pom.xml
[MODINVOICE-289] - 5.1.4 R2 Bugfix release …
> [MODINVOICE-289] - 5.1.4 R2 Bugfix release

- pom.xml
- src/main/java/org/folio/models/InvoiceHolder.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/util/InvoiceHolder.java
Invoice poNumbers needs to be updated when an invoice line is deleted.
Update InvoiceLineHelper#deleteInvoiceLine to add a call to InvoiceLineHelper#updateInvoicePoNumbers.
Update unit tests and cross-module integration tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> [MODINVOICE-275] Invoice poNumbers needs to be updated when an invoice line is deleted

- descriptors/ModuleDescriptor-template.json
[MODFISTO-244](https://issues.folio.org/browse/MODFISTO-244) - Add validation for special character to Fund Code and Expense class code and prepare migration script
Updated finance.expense-classes API version and acq-models.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> [MODFISTO-244] Updated API for expense classes

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
https://issues.folio.org/browse/MODINVOICE-290
* added missed permission
While it's …
> MODINVOICE-290 added missed permission

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/FAT-953
* found missed permission
* added missed permission …
> FAT-953 added missed permission

- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
To fix the issue that occurs when changed fund is being saved with same encumbrance id.
Unlink encumbrance if the fund is changed. …
> MODINVOICE-290 - unlink encumbrances from changed funds

- pom.xml
- src/main/java/org/folio/jaxb/JAXBContextWrapper.java
https://issues.folio.org/browse/MODINVOICE-308
* added missed jaxb dependencies
While …
> MODINVOICE-308 added missed jaxb dependencies

- src/main/java/org/folio/services/VoucherLinesRetrieveService.java
[MODINVOICE-312](https://issues.folio.org/browse/MODINVOICE-312)
Taking into consideration that voucher lines should not exceed 100 per voucher, reduced the number of vouchers to query by chunk, and removed the limit on returned voucher lines.
Include in Juniper hotfix.
Ideally all of the PRs involved in breaking changes would be merged in the same day …
> [MODINVOICE-312] Fixed missing batch voucher lines

- src/main/java/org/folio/invoices/events/handlers/BatchVoucherProcessHandler.java
- src/main/java/org/folio/services/voucher/UploadBatchVoucherExportService.java
Display Batch export status as "Generated" when export created
Added the display "Generated" when export created in the absence of credentials  …
> [MODINVOICE-313] - Displayed "Generated" when export created

- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
https://issues.folio.org/browse/MODINVOICE-318
* switched polines searches to sequential mode …
> Modinvoice-318 Creating multiple large invoices quickly from Data Import failed

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/main/java/org/folio/rest/impl/BatchVoucherPersistHelper.java
[MODINVOICE-318
](https://issues.folio.org/browse/MODINVOICE-318)
* increased allocated memory in order to process large invoices …
> MODINVOICE-318 increase memory size

- src/main/java/org/folio/dataimport/handlers/events/DataImportKafkaHandler.java
JIRA: https://issues.folio.org/browse/MODDATAIMP-491
We can change meaningless kafka header "correllationId" to "recordId" and "chunkId".
This changes have to be added to the: data-import, data-import-processing-core, srm, srs, inventory  and other core modules.
Logs improved for showing ids.
> MODDATAIMP-491: Improve logging.

- ramls/schemas/batch_voucher.xsd
Unable to download batch vouchers
While it's helpful for reviewers to help identify …
> [MODINVOICE-347] - Fixed the error of download batch  vouchers

- pom.xml
to pick up changes for currency mapping
[MODDICORE-225](https://issues.folio.org/browse/MODDICORE-225)
> MODDICORE-225 - Update di-core library

- pom.xml
https://issues.folio.org/browse/MODINVOICE-348 …
> MODINVOICE-348. Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
KIWI R3 2021 Bugfix release
While it's helpful for reviewers to help identify potential …
> [MODINVOICE-351] - KIWI Bugfix 5.2.4

- src/main/java/org/folio/services/finance/transaction/PaymentCreditWorkflowService.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
[MODINVOICE-346](https://issues.folio.org/browse/MODINVOICE-346) - Approving an invoice with multiple lines that ref the same POL 2 payment 1 credit. Causes over reported encumbrance value on budget
To work around mod-finance lack of support for parallel processing, transactions are created in sequence.
Note that errors are random. The related integration test does not always fail before the fix.
Fix mod-finance and/or mod-finance-storage.
- Do JIRAs exist to update the impacted …
> [MODINVOICE-346] Create transactions in sequence as workaround

- pom.xml
https://issues.folio.org/browse/MODINVOICE-349 …
> MODINVOICE-349. Juniper R2 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-350 …
> MODINVOICE-350. Juniper R2 2021 HF #5 module release

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/voucher/VoucherCommandService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/TestMockDataConstants.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
[MODINVOICE-270](https://issues.folio.org/browse/MODINVOICE-270) - Cancel invoice : create logic to support invoice cancel operation
- New status transition to cancel invoices
- New service to cancel invoices
- Validate that only approved and paid invoices can be cancelled
- Update pending payments, payments, credits, invoice lines and voucher (using [MODFIN-230](https://issues.folio.org/browse/MODFIN-230) changes to update payments and credits)
- Unit tests
InvoiceCancelServiceTest avoids using the MockServer so that all the testing code is encapsulated in the class. Instead it is using mocks with the rest client, and the new argument matcher argThat (which I have not seen in use anywhere else in the acquisition code). A downside is that service initialization is a bit heavy (but limited …
> [MODINVOICE-270] New logic to cancel invoices

- src/main/java/org/folio/services/validator/FundAvailabilityHolderValidator.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/services/validator/FundAvailabilityHolderValidatorTest.java
> MODINVOICE-357-Error_message_does_not_indicate_what_Fund_does_not_have_money_in_MOD-INVOICE

- ramls/examples/batch_voucher_sample.xml
- ramls/schemas/batch_voucher.xsd
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/converters/BatchedVoucherModelConverter.java
- src/main/java/org/folio/services/InvoiceLinesRetrieveService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/converters/BatchedVoucherModelConverterTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/InvoiceLinesRetrieveServiceTest.java
- src/test/java/org/folio/services/voucher/BatchVoucherGenerateServiceTest.java
- src/test/resources/mockdata/batchVouchers/35657479-83b9-4760-9c39-b58dcd02ee14.json
Add adjustment detail to voucher when "Export" is true for adjustment
We are get:
- All adjustments from invoice where flag "Export to accounting" = true
- All unique adjustments from invoiceLine where flag "Export to accounting" = true
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> [MODINVOICE-336] - Added adjustment detail to voucher when "Export" is true for adjustment

- descriptors/ModuleDescriptor-template.json
- ramls/examples/batch_voucher_sample.xml
- ramls/schemas/batch_voucher.xsd
- src/main/java/org/folio/converters/BatchedVoucherModelConverter.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/resources/mockdata/batchVouchers/35657479-83b9-4760-9c39-b58dcd02ee14.json
- src/test/resources/mockdata/invoiceLines/invoice_lines.json
- src/test/resources/mockdata/invoices/invoices.json
Calculate adjustment total amount
While it's helpful for reviewers to help identify …
> [MODINVOICE-336] - Calculation adjustment total amount

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/services/finance/transaction/OrderTransactionSummaryService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/order/OrderLineService.java
- src/main/java/org/folio/services/order/OrderService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
[MODINVOICE-360](https://issues.folio.org/browse/MODINVOICE-360) - Unrelease auto-released encumbrances when cancelling an invoice
See Jira ticket.
[MODFIN-236](https://issues.folio.org/browse/MODFIN-236) - Missing permissions for payment/credit PUT
Implementing this would have been easier with [MODFISTO-268](https://issues.folio.org/browse/MODFISTO-268) because the transaction summary id would not need to be an order id or an invoice id. Even though we are cancelling an invoice, we have to use an order transaction summary to modify the encumbrances. Also this implementation will have to be updated after we implement MODFISTO-268.
There is an issue when using Mockito to stub methods returning a null value: because the default mock returns a null value, we cannot know if the given stub was …
> [MODINVOICE-360] Unrelease encumbrances when cancelling invoice

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODINVOICE-362
While it's …
> MODINVOICE-362 Lotus 2022 R1 module release 5.3.0

- descriptors/ModuleDescriptor-template.json
[MODINVOICE-369](https://issues.folio.org/browse/MODINVOICE-369) - Undefined permission 'invoice.invoice-number.item.post'
Removed permission reference from `invoice.all`.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> [MODINVOICE-369] Removed reference to undefined permission

- pom.xml
to support the "hidden" field in the profiles
Update version of data-import-processing-core
MODINVOICE-372: Update version of data-import-processing-core
> MODINVOICE-372: Update version of data-import-processing-core

- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
https://issues.folio.org/browse/MODINVOICE-363 …
> MODINVOICE-363. Can not pay invoice that references the same POL and 2 different invoice lines

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/services/voucher/UploadBatchVoucherExportService.java
> [MODINVOICE-379] - Export run is showing a permission error

- src/main/java/org/folio/services/validator/FundAvailabilityHolderValidator.java
Fix what no money can be expended when fully encumbered
While it's helpful for reviewers …
> [MODINVOICE-367] - Calculation of encumbrance

- descriptors/ModuleDescriptor-template.json
> [MODINVOICE-367] - Add permission descriptions

- src/main/java/org/folio/services/finance/transaction/EncumbranceService.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
[MODINVOICE-385](https://issues.folio.org/browse/MODINVOICE-385) - Cancel only unreleased 1 encumbrance from an invoice line
Fixed bug in `EncumbranceService.getEncumbrancesByPoLineIds()` : more than 1 encumbrance may be associated to a given po line.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> [MODINVOICE-385] Retrieve more than one encumbrance per po line

- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/services/invoice/InvoicePaymentService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
[MODINVOICE-387](https://issues.folio.org/browse/MODINVOICE-387) - Insufficient fund validation to approve invoice
- After the budgets are retrieved, check that they only use a single fiscalYearId.
- Return an error message with 2 related fund codes otherwise.
- New unit test.
Ideally all of the PRs involved in breaking changes would be merged in the …
> [MODINVOICE-387] Approval/payment: check that a single fiscal year is used

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/AbstractHelper.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
- Updated schemas
- Updated affected API versions
- Report a 409 if a 409 is returned from mod-finance.
- Made sure a transaction update uses the previous version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> [MODFISTO-303] update for finance optimistic locking

- descriptors/ModuleDescriptor-template.json
Added permissions to work with this endpoint POST /invoice/invoice-lines
While it's …
> [MODINVOICE-402] - added permissions for POST /invoice/invoice-lines

- src/main/java/org/folio/invoices/utils/InvoiceUnprotectedFields.java
- src/main/java/org/folio/services/validator/InvoiceValidator.java
> [MODINVOICE-401]-Modified InvoiceValidator class

- pom.xml
https://issues.folio.org/browse/MODINVOICE-410 …
> MODINVOICE-410 Upgrade RAML Module Builder

- src/main/java/org/folio/services/FundsDistributionService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/resources/mockdata/invoiceLines/8a1dc57e-8857-4dc3-bdda-871686e0b98b.json
- src/test/resources/mockdata/invoices/b8862151-6aa5-4301-aa1a-34096a03a5f7.json
- src/test/resources/mockdata/voucherLines/voucher_lines_for_move_payment.json
- src/test/resources/mockdata/vouchers/9ebe5abc-1565-48e0-8531-ae03e83815ca.json
Can not paid for the Invoice where one of the amount is negative …
> [MODINVOICE-411] - Paid for the Invoice where one of the amount is negative

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/MODINVOICE-405
While it's …
> MODINVOICE-405 release notes v5.4.0 Morning Glory 2022 R2

- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/services/validator/InvoiceValidator.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
https://issues.folio.org/browse/MODINVOICE-417
Provide new endpoint to validate fund distributions for a Invoice line & adjustments that will be called by UI to have consistent validation with BE
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> [Modinvoice 417]-changed error code

- pom.xml
> [MODINVOICE-430]-upgraded RMB

- NEWS.md
- pom.xml
> [MODINVOICE-433] - Release 5.5.0

- NEWS.md
- src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java
https://issues.folio.org/browse/MODINVOICE-435
> [MODINVOICE-435] Module release Morning Glory R2 2022 Hot Fix #1

- src/main/java/org/folio/services/exchange/ManualExchangeRateProvider.java
- src/main/java/org/folio/services/finance/FundService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/validator/InvoiceValidator.java
- src/main/java/org/folio/services/voucher/VoucherCommandService.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
> [MODINVOICE-428]-updated error codes

- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
https://issues.folio.org/browse/MODINVOICE-442 …
> [MODINVOICE-442]-URI Too Long exception fixed.

- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
[MODINVOICE-446](https://issues.folio.org/browse/MODINVOICE-446) - Encumbrance for Ongoing order remains "Released" after cancelling related invoice
Added the "`Ongoing`" value to the filter by `paymentStatus`.
See [integration test](https://github.com/folio-org/folio-integration-tests/pull/839).
Ideally, all the PRs involved in breaking changes would be …
> [MODINVOICE-446] Cancel invoice unreleases encumbrances of ongoing orders

- src/main/java/org/folio/rest/impl/FundDistributionsValidationHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
https://issues.folio.org/browse/MODINVOICE-449 …
> [MODINVOICE-449]-updated fundValidation

- NEWS.md
- pom.xml
> [MODINVOICE-451] - Release v5.6.0

- pom.xml
Update mod-di-converter-storage-client and data-import-processing-core dependencies
Updated dependencies
> [MODDICORE-306] Update mod-di-converter-storage-client and data-import-processing-core dependencies

- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
https://issues.folio.org/browse/MODINVOICE-460
* fixed vertx semaphores usage
While it's …
> MODINVOICE-460 fixed vertx semaphores

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/ResourcePathResolver.java
https://issues.folio.org/browse/MODINVOICE-467
* switched acq units calls to the storage endpoints
especially as the number of inter-module and inter-team dependencies …
> MODINVOICE-467 switched acq units calls to the storage endpoints

- descriptors/ModuleDescriptor-template.json
- ramls/invoice.raml
- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/main/java/org/folio/services/finance/budget/BudgetService.java
- src/main/java/org/folio/services/finance/fiscalyear/FiscalYearService.java
- src/main/java/org/folio/services/invoice/InvoiceFiscalYearsService.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/services/invoice/InvoiceFiscalYearsServiceTest.java
[MODINVOICE-465](https://issues.folio.org/browse/MODINVOICE-465) - Provide endpoint to retrieve fiscal year for invoice
- Added the endpoint in the raml and module descriptor, with a new permission
- Used minimal code in the invoice helper
- Put most of the new implementation in a new service, `InvoiceFiscalYearsService`
- Return fiscal years that have active budgets for all the funds in the invoice (excluding future fiscal years), sorted by `periodStart`
- Return a 422 error if no such fiscal year is found or if matching fiscal years are in more than one series
- New unit tests
[Integration test](https://github.com/folio-org/folio-integration-tests/pull/914)
See comments in [MODINVOICE-465](https://issues.folio.org/browse/MODINVOICE-465).
Before merging this PR, please go through the …
> [MODINVOICE-465] Invoice Fiscal Years

- src/main/java/org/folio/invoices/rest/exceptions/ExceptionUtil.java
> [MODFISTO-405] - fix for errors message json

- NEWS.md
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
> [MODINVOICE-472] - Release v5.5.1

- pom.xml
update data-import-processing-core library to pick up changes in the action profile schema (introduced  in the https://github.com/folio-org/mod-di-converter-storage/pull/11)
> Update di-processing-core dependency

- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/rest/impl/BatchVoucherExportConfigurationsImpl.java
- src/main/java/org/folio/rest/impl/BatchVoucherPersistHelper.java
- src/main/java/org/folio/services/InvoiceLinesRetrieveService.java
- src/main/java/org/folio/services/invoice/InvoiceLineService.java
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
https://issues.folio.org/browse/MODINVOICE-480
* fixed NPE in error handler
* fixed invoice lines retrieving
especially as the number of inter-module and inter-team …
> MODINVOICE-480 fixed NPE in error handler

- src/main/java/org/folio/jaxb/XMLConverter.java
- src/main/java/org/folio/rest/impl/UploadBatchVoucherExportHelper.java
- src/main/java/org/folio/services/ftp/FtpUploadService.java
- src/main/java/org/folio/services/voucher/BatchVoucherService.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/services/voucher/UploadBatchVoucherExportServiceTest.java
https://issues.folio.org/browse/MODINVOICE-480
* ftp upload failed because of broken spring autowiring mechanism
* fixed spring context init
especially as the number of …
> MODINVOICE-480 fixed spring context init

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/AcqDesiredPermissions.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/utils/UserPermissionsUtil.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/InvoicesApiTest.java
- src/test/resources/mockdata/invoices/8c92f2a1-67e3-4cfe-ba02-ba16404f7f1c.json
- src/test/resources/mockdata/invoices/ff634ec9-67fd-4239-9f2b-91d15bb2a996.json
Restrict approving/paying an invoice against past fiscal year with a new permission
While it's …
> [MODINVOICE-471] - Restrict approving/paying an invoice

- descriptors/ModuleDescriptor-template.json
> [MODINVOICE-471] - Add permission description

- src/main/java/org/folio/services/ftp/SftpUploadService.java
- src/test/java/org/folio/services/ftp/SftpUploadServiceTest.java
> [MODINVOICE-454-2]-Added default directory for sftp

- src/main/java/org/folio/services/validator/FundAvailabilityHolderValidator.java
- src/test/java/org/folio/services/validator/FundAvailabilityHolderValidatorTest.java
Invoice cannot be approved when balance is close to the encumbrance available balance
While …
> [MODINVOICE-477] - Invoice approve when balance is close to the encumbrance available balance

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
* paralel threads cause database overloading and isues with creating order-invoice relationships
* limit semaphore active threads
especially as the number of inter-module and …
> limit semaphore with 1 thread

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandler.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
> release notes v5.6.5 (Orchid R1 Technical debt)

- Dockerfile
- Jenkinsfile
- pom.xml
https://issues.folio.org/browse/MODINVOICE-484 …
> [MODINVOICE-484]-updated to java 17

- Dockerfile
- Jenkinsfile
- pom.xml
Reverts folio-org/mod-invoice#424
> Revert "[MODINVOICE-484]-updated to java 17"

- src/main/java/org/folio/services/validator/InvoiceValidator.java
When users try to approve invoice which contains invoice lines with undistributed amount the error message is non informative:
- Passed invoice line number in case fund distribution validation for approve
[MODINVOICE-488](https://issues.folio.org/browse/MODINVOICE-488)
to …
> [MODINVOICE-488] - Invoice cannot be approved when an invoice-line is multi-fund distributed by amounts with an invoice-level adjustment

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-504](https://issues.folio.org/browse/MODINVOICE-504) - mod-invoice: module release …
> [MODINVOICE-504] - Release v5.7.0

- descriptors/ModuleDescriptor-template.json
> [MODINVOICE-508] - Add invoice.item.cancel permission

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODINVOICE-508](https://issues.folio.org/browse/MODINVOICE-508) - mod-invoice 5.7.1: module release
especially as the number of inter-module and inter-team dependencies …
> [MODINVOICE-508] - Release v5.7.1

- pom.xml
- src/test/java/org/folio/ApiTestSuite.java
https://issues.folio.org/browse/MODINVOICE-502
> MODINVOICE-502. Update RMB and vertx to the latest version

- src/main/java/org/folio/InvoiceWorkflowDataHolderBuilder.java
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/invoice/InvoicePaymentService.java
- src/test/java/org/folio/TestMockDataConstants.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
- src/test/resources/mockdata/budgets/budget.json
The main issue was the missing condition that should check the budget status before cancellation. In the previous implementation, the user was able to cancel the invoice even in 'Closed' or 'Inactive' budget statuses.
- Added validation to check budget status
- Refactored InvoiceWorkflowHolderBuilder
[MODINVOICE-509](https://issues.folio.org/browse/MODINVOICE-509)
- Do PRs exist for these …
> [MODINVOICE-509] - Invoice cancellation allowed against closed budget

- NEWS.md
- pom.xml
- src/main/java/org/folio/verticles/DataImportConsumerVerticle.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
- src/test/java/org/folio/verticles/DataImportConsumerVerticleTest.java
Remove step of initial saving of incoming records to SRS
Migrate from DI_EDIFACT_RECORD_CREATED to DI_INCOMING_EDIFACT_RECORD_PARSED event
especially as the number of …
> MODSOURMAN-1022: migrate from DI_EDIFACT_RECORD_CREATED to DI_INCOMING_EDIFACT_RECORD_PARSED event

- NEWS.md
- pom.xml
- src/main/java/org/folio/verticles/DataImportConsumerVerticle.java
- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
- src/test/java/org/folio/verticles/DataImportConsumerVerticleTest.java
This reverts commit 7fc897a1ef5bdbcaea2126a4c6c7cf4dd74c2f4d.
While it's helpful for reviewers …
> Revert "MODSOURMAN-1022: migrate from DI_EDIFACT_RECORD_CREATED to DI_INCOMING_EDIFACT_RECORD_PARSED event (#449)"

- descriptors/ModuleDescriptor-template.json
broken hourly platform build mod-invoice [MODINVOICE-520](https://issues.folio.org/browse/MODINVOICE-520)
add additional endpoints on _tenant interface
> MODINVOICE-520 broken hourly platform build mod-invoice

- src/main/java/org/folio/services/validator/FundAvailabilityHolderValidator.java
- src/test/java/org/folio/services/validator/FundAvailabilityHolderValidatorTest.java
> [MODINVOICE-533] - Change restricted expenditures calculations

- pom.xml
- src/test/java/org/folio/builders/InvoiceWorkFlowDataHolderBuilderTest.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/schemas/xsd/BatchVoucherSchemaXSDTest.java
- src/test/java/org/folio/services/finance/transaction/BaseTransactionServiceTest.java
https://folio-org.atlassian.net/browse/MODINVOICE-531
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
> [MODINVOICE-531] Upgrade RAML Module Builder

- pom.xml
Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md
> MODINVOICE-531. Upgrade to the latest version of folio-di-support

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODINVOICE-535 …
> [MODINVOICE-535] - Release v5.8.0

- descriptors/ModuleDescriptor-template.json
[MODINVOICE-516](https://folio-org.atlassian.net/browse/MODINVOICE-516) - Invoice transactions should not be changed when acquisition check was failed
Using a permission to bypass orders acq unit checks when updating an invoice (for instance when an invoice is paid).
[Related mod-orders PR](https://github.com/folio-org/mod-orders/pull/871)
[Related integration test](https://github.com/folio-org/folio-integration-tests/pull/1299)
- …
> [MODINVOICE-516] Using a permission to bypass orders acqunit checks

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/AcqDesiredPermissions.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
- src/main/java/org/folio/rest/impl/ProtectionHelper.java
- src/main/java/org/folio/utils/UserPermissionsUtil.java
- src/test/java/org/folio/rest/impl/protection/InvoicesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/LinesProtectionTest.java
- src/test/java/org/folio/rest/impl/protection/ProtectedEntityTestBase.java
[MODORDERS-1073](https://folio-org.atlassian.net/browse/MODORDERS-1073) - Invoice encumbrance link not removed because of acquisition unit
Added a new permission, similar to MODINVOICE-516.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/873) - [integration test](https://github.com/folio-org/folio-integration-tests/pull/1304)
Ideally, all the …
> [MODORDERS-1073] Added a permission to bypass acqunit checks

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/invoice/InvoiceLineService.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
[MODINVOICE-537](https://folio-org.atlassian.net/browse/MODINVOICE-537) - POL payment status not updated when invoice is cancelled
See algorithm in the ticket.
[Integration test](https://github.com/folio-org/folio-integration-tests/pull/1310)
to avoid breaking the …
> [MODINVOICE-537] Update po lines paymentStatus when cancelling invoices

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODFIN-358
> MODFIN-358. Upgrade finance.funds interface

- descriptors/ModuleDescriptor-template.json
[MODFIN-352](https://folio-org.atlassian.net/browse/MODFIN-352) - Remove the old transaction API
Updated finance API version
[mod-finance PR](https://github.com/folio-org/mod-finance/pull/245)
Communication is paramount if that …
> [MODFIN-352] Updated finance API version support

- NEWS.md
- pom.xml
> Bug Fix Release v5.8.2

- src/test/java/org/folio/dataimport/handlers/actions/CreateInvoiceEventHandlerTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1014 …
> Updated acq-modeles to include fix for isBindaryActive field

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/invoices/utils/AcqDesiredPermissions.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/utils/UserPermissionsUtilTest.java
> MODINVOICE-556 clean up permissions

- ramls/invoice.raml
https://folio-org.atlassian.net/browse/MODINVOICE-557
> MODINVOICE-557. API doc has wrong input for POST /invoice/invoices/{id}/documents

- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/services/adjusment/AdjustmentsService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoiceLinesProratedAdjustmentsTest.java
- src/test/java/org/folio/rest/impl/InvoicesProratedAdjustmentsTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-554>
- Include adjustments into total and adjustment total calculation
- <https://github.com/folio-org/mod-invoice/pull/509>
- <https://github.com/folio-org/folio-integration-tests/pull/1563>
- <https://github.com/folio-org/folio-integration-tests/pull/1565>
> [MODINVOICE-554-2]. Change invoice total and adjustments total calculation

- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/services/adjusment/AdjustmentsService.java
- src/test/java/org/folio/rest/impl/InvoiceLinesApiTest.java
- src/test/java/org/folio/rest/impl/InvoiceLinesProratedAdjustmentsTest.java
- src/test/java/org/folio/rest/impl/InvoicesProratedAdjustmentsTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-554>
- Revert 2 PR changes
- There is some difficulty in including VAT calculation as an adjustment
> [MODINVOICE-554-revert]. Revert 2 PR changes

- pom.xml
- src/main/java/org/folio/rest/impl/UploadBatchVoucherExportHelper.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/services/ftp/SftpUploadServiceTest.java
[[MODINVOICE-562] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODINVOICE-562)
- Update versions
- Add module descriptor validator
> [MODINVOICE-562] Update libraries of dependant acq modules to the latest versions

- NEWS.md
- pom.xml
- src/main/java/org/folio/services/voucher/BatchVoucherGenerateService.java
- src/test/java/org/folio/rest/impl/MockServer.java
Release Ramsons 5.9.1 Bug Fix that includes this ticket:
https://folio-org.atlassian.net/browse/MODINVOICE-566
> Ramsons Bug Fix release v5.9.1

- src/main/java/org/folio/rest/core/InvoiceDocumentRestClient.java
- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/rest/impl/BatchGroupsImpl.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/main/java/org/folio/rest/impl/VouchersImpl.java
- src/main/java/org/folio/services/configuration/ConfigurationService.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1227>
- Remove sensitive logs that can potentially leak PIIs
- Search parameters:
- `src/main/java` path
- `log.info`, `log.debug`, `log.warn`, `log.error`, `log.trace` markers
- `logger.info`, `logger.debug`, `logger.warn`, `logger.error`, `logger.trace`  markers
- `JsonObject.mapFrom`, `JsonArray.of()` markers
> [MODORDERS-1227]. Perform a new round of deletion of sensitive information from logs in acq modules

- Dockerfile
- Jenkinsfile
- pom.xml
[[FOLIO-4207] Update to mod-invoice Java 21](https://folio-org.atlassian.net/browse/FOLIO-4207)
Update java and dependency versions
> [FOLIO-4207] Update to mod-invoice Java 21

- pom.xml
[[FOLIO-4207] Update to mod-invoice Java 21](https://folio-org.atlassian.net/browse/FOLIO-4207)
Update maven-compiler-plugin to Java 21
> [FOLIO-4207] Update maven-compiler-plugin to Java 21

- NEWS.md
- pom.xml
Make Sunflower R1 2025 release
> Sunflower release v6.0.0

- ramls/invoice.raml
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/invoices/utils/ErrorCodes.java
- src/main/java/org/folio/invoices/utils/HelperUtils.java
- src/main/java/org/folio/rest/impl/InvoiceHelper.java
- src/main/java/org/folio/rest/impl/InvoicesImpl.java
- src/main/java/org/folio/services/invoice/InvoiceApprovalService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/services/invoice/InvoiceFundDistributionService.java
- src/main/java/org/folio/services/invoice/PoLinePaymentStatusUpdateService.java
- src/main/java/org/folio/services/order/OrderLineService.java
- src/main/java/org/folio/services/order/OrderService.java
- src/main/java/org/folio/services/validator/InvoiceValidator.java
- src/main/java/org/folio/services/voucher/VoucherCreationService.java
- src/main/java/org/folio/utils/FutureUtils.java
- src/test/java/org/folio/ApiTestSuite.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
- src/test/java/org/folio/services/invoice/PoLinePaymentStatusUpdateServiceTest.java
- src/test/java/org/folio/services/order/OrderLineServiceTest.java
- src/test/java/org/folio/services/validator/InvoiceValidatorServiceTest.java
[MODINVOICE-573](https://folio-org.atlassian.net/browse/MODINVOICE-573) - Updating order status when approving or cancelling an invoice against a previous fiscal year
- New parameter: `poLinePaymentStatus`
- New service gathering all po line `paymentStatus` updates: `PoLinePaymentStatusUpdateService` (including the ones previously used when cancelling an invoice)
- Refactoring: creation of other services to reduce `InvoiceHelper` but still avoid code duplication (`InvoiceApprovalService`, `InvoiceFundDistributionService`, `VoucherCreationService`)
- New validation to ensure the new parameter is used when required (but no check if it is present)
- New implementation of `paymentStatus` updates when `poLinePaymentStatus` is used
- Unit test updates and new unit tests
[Integration tests …
> [MODINVOICE-573] Update po line paymentStatus when approving or cancelling an invoice against a previous fiscal year

- src/main/java/org/folio/dataimport/utils/DataImportUtils.java
Change SYSTEM_USER_ENABLED configuration reading in the data-import-utils
added reading values from environment variables
[MODINVOICE-591](https://folio-org.atlassian.net/browse/MODINVOICE-591)
> MODINVOICE-591: SYSTEM_USER_ENABLED env var implementation via standard mechanism, not via JAVA_OPTS

- NEWS.md
- pom.xml
- src/main/java/org/folio/services/voucher/BatchVoucherService.java
- src/test/java/org/folio/rest/impl/BatchVoucherImplTest.java
Includes fix https://folio-org.atlassian.net/browse/MODINVOICE-595
_Provide a brief technical summary of the changes._
---
> Ramsons v 5.9.3 release

- NEWS.md
- pom.xml
- src/main/java/org/folio/services/voucher/BatchVoucherService.java
- src/test/java/org/folio/rest/impl/BatchVoucherImplTest.java
Includes ticket https://folio-org.atlassian.net/browse/MODINVOICE-601
_Provide a brief technical summary of the changes._
---
> Sunflower v6.0.2 release

- src/main/java/org/folio/services/finance/transaction/EncumbranceService.java
- src/test/java/org/folio/services/finance/transaction/EncumbranceServiceTest.java
https://folio-org.atlassian.net/browse/MODINVOICE-603
_Provide a brief technical summary of the changes._
---
> MODINVOICE-603. Prevent having duplicated transactions for update

- src/main/java/org/folio/services/finance/EncumbranceUtils.java
- src/main/java/org/folio/services/finance/transaction/BaseTransactionService.java
- src/main/java/org/folio/services/finance/transaction/EncumbranceService.java
- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/main/java/org/folio/utils/MoneyUtils.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-613>
- Add reversal of credit amount on the encumbrance during invoice cancellation
- Add related Karate tests
- <https://github.com/folio-org/folio-integration-tests/pull/2023>
- Add unit tests
> [MODINVOICE-613]. Incorrect encumbrances on orders with paid and cancelled invoices

- src/main/java/org/folio/services/invoice/InvoiceCancelService.java
- src/test/java/org/folio/services/invoice/InvoiceCancelServiceTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-613>
- Manually revert credit reversal with the unit tests
- Add related Karate tests
- <https://github.com/folio-org/folio-integration-tests/pull/2036>
> [MODINVOICE-613-2]. Incorrect encumbrances on orders with paid and cancelled invoices
